### PR TITLE
chore: Added throws clause Fixes #598

### LINKED ISSUE #598: Missing throws clauses
```
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\AuthorizationCodeInstalledApp.java:47:43: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\AuthorizationCodeInstalledApp.java:98:53: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\FileCredentialStore.java:69:73: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\FileCredentialStore.java:106:54: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\FileCredentialStore.java:187:77: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\FileCredentialStore.java:197:87: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\VerificationCodeReceiver.java:30:34: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\VerificationCodeReceiver.java:33:31: Expected @throws tag for 'IOException'. [JavadocMethod]
[WARN] D:\a\google-oauth-java-client\google-oauth-java-client\google-oauth-client-java6\src\main\java\com\google\api\client\extensions\java6\auth\oauth2\VerificationCodeReceiver.java:36:22: Expected @throws tag for 'IOException'. [JavadocMethod]
Audit done.
```

### PR DESCRIPTION
**Pull request by schrosolver**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-oauth-java-client/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #598 ☕️

### CODE REVIEW

**Comment by schrosolver** [comment]
@googlebot I fixed it.

**Comment by chanseokoh** [comment]
@schrosolver looks like there's an inherent issue with the build infrastructure. Not sure why it's manifesting here.

**Comment by lesv** [comment]
# ci / lint
```
Error:  Failed to execute goal com.coveo:fmt-maven-plugin:2.12:check (default-cli) on project google-oauth-client: Execution default-cli of goal com.coveo:fmt-maven-plugin:2.12:check failed: An API incompatibility was encountered while executing com.coveo:fmt-maven-plugin:2.12:check: java.lang.NoSuchMethodError: null
Error:  -----------------------------------------------------
Error:  realm =    plugin>com.coveo:fmt-maven-plugin:2.12
Error:  strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Error:  urls[0] = file:/home/runner/.m2/repository/com/coveo/fmt-maven-plugin/2.12/fmt-maven-plugin-2.12.jar
Error:  urls[1] = file:/home/runner/.m2/repository/com/google/googlejavaformat/google-java-format/1.7/google-java-format-1.7.jar
Error:  urls[2] = file:/home/runner/.m2/repository/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar
Error:  urls[3] = file:/home/runner/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
Error:  urls[4] = file:/home/runner/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
Error:  urls[5] = file:/home/runner/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
Error:  urls[6] = file:/home/runner/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar
Error:  urls[7] = file:/home/runner/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar
Error:  urls[8] = file:/home/runner/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
Error:  urls[9] = file:/home/runner/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar
Error:  urls[10] = file:/home/runner/.m2/repository/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.jar
Error:  urls[11] = file:/home/runner/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
Error:  urls[12] = file:/home/runner/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
Error:  urls[13] = file:/home/runner/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
Error:  urls[14] = file:/home/runner/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
Error:  urls[15] = file:/home/runner/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
Error:  urls[16] = file:/home/runner/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
Error:  Number of foreign imports: 1
Error:  import: Entry[import  from realm ClassRealm[project>com.google.oauth-client:google-oauth-client-parent:1.32.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
Error:  
Error:  -----------------------------------------------------
Error:  : com.google.googlejavaformat.java.ImportOrderer.reorderImports(Ljava/lang/String;Lcom/google/googlejavaformat/java/JavaFormatterOptions$Style;)Ljava/lang/String;
```

**Comment by TimurSadykov** [comment]
@lesv @chanseokoh  this fixes the build: https://github.com/googleapis/google-oauth-java-client/pull/768

**Comment by schrosolver** [comment]
@chanseokoh can you please rerun the checks, after the PR #768 is merged, did a rebase again on this.

**Review by chanseokoh — APPROVED** [review]

**Pull request merged**
